### ISSUE TITLE
how to debug a startup script

### ISSUE THREAD

**Issue by cyb3ralbert** [terraform-google-modules/terraform-google-startup-scripts#30]
Any idea how to debug execution of a startup script?

I already tried 

```
exec 5> >(systemd-cat -t $0)
BASH_XTRACEFD="5"
PS4='$LINENO: '
set -x

```

without any success

**Comment by morgante** [comment]
You can check the syslog for details.

Or SSH into the VM and re-excute the script: https://cloud.google.com/compute/docs/startupscript#rerunthescript

**Comment by cyb3ralbert** [comment]
I forgot to say, that I already checked journalctl and found nothing. 

I'll try the the second thing. Thanks.

**Comment by cyb3ralbert** [comment]
`google_metadata_script_runner --script-type startup --debug` works just fine
